In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline
%autosave 300

Autosaving every 300 seconds


In this notebook we will focus on fundamentals of pytorch and tensor operations.

In [1]:
import torch
import matplotlib.pyplot as plt

In [2]:
# Rank-0 tensor
a = torch.tensor(1)
print(a)
print(a.shape)
print(a.ndim)

tensor(1)
torch.Size([])
0


In [ ]:
# rank-1 tensor
b = torch.tensor([1,2,3,4])
print(b)
print(b.shape)
print(b.ndim)
print(b.dtype)
# changing datatype of tensor
b = b.to(torch.int32)
print(b)
print(b.dtype)

tensor([1, 2, 3, 4])
torch.Size([4])
1
torch.int64
tensor([1, 2, 3, 4], dtype=torch.int32)
torch.int32


In [ ]:
# rank-2 tensor 
c = torch.tensor([[1.2,2.1,3.6],
                    [4.5,5.9,6.7],
                    [7.8,8.3,9.0]])

print(c)
print(c.ndim)
print(c.shape)
print(c.dtype)
print(c.device)
# changing datatype of tensor
c = c.to(torch.float16)
print(c)
print(c.dtype)


tensor([[1.2000, 2.1000, 3.6000],
        [4.5000, 5.9000, 6.7000],
        [7.8000, 8.3000, 9.0000]])
2
torch.Size([3, 3])
torch.float32
cpu
tensor([[1.2002, 2.0996, 3.5996],
        [4.5000, 5.8984, 6.6992],
        [7.8008, 8.2969, 9.0000]], dtype=torch.float16)
torch.float16
